/**
 * On-chain Oracle client — reads prices from the deployed Oracle.sol contract.
 *
 * Reads from the Arc Network Testnet Oracle (Chain ID 5042002), where we
 * deployed a fresh Oracle.sol that correctly implements goldPrice() and
 * silverPrice(). The Monad Testnet Oracle (0xDfcA...) bytecode does not match
 * our source — all reads revert — so we use the Arc Oracle as the live
 * on-chain price source.
 *
 * Constitutional context (§30-33 v23):
 *   The Constitution requires a multi-oracle consensus. This is the testnet
 *   single-source on-chain implementation. On mainnet, this will be replaced
 *   by a MultiOracleConsensus adapter aggregating Chainlink + Pyth + Chronicle.
 *
 * Fallback strategy:
 *   - If MOCK_ORACLE_ADDRESS is set AND the contract responds, use on-chain prices
 *   - Otherwise, fall back to live free APIs (gold-api.com, open.er-api.com)
 *   - This ensures the dashboard always shows real prices even if the on-chain
 *     Oracle is unreachable or stale.
 *
 * Price encoding: 8 decimals (matches Oracle.sol conventions)
 *   $4053.50 = 4053_50000000 = 405350000000 wei
 */

const ORACLE_RPC = "https://rpc.testnet.arc.io"; // Arc Network Testnet (Chain ID 5042002)

// Function selectors (first 4 bytes of keccak256(signature))
const SELECTORS = {
  goldPrice: "0x44501404", // goldPrice() — public variable auto-getter
  silverPrice: "0xff391c06", // silverPrice()
  getGoldPrice: "0xda6bae10", // getGoldPrice()
  getSilverPrice: "0x4e279b79", // getSilverPrice()
  getStablecoinPrice: "0x84176e95", // getStablecoinPrice(string)
  lastUpdated: "0x233af1b0", // lastUpdated(string)
};

export interface OraclePrice {
  asset: string;
  priceUsd: number;
  decimals: number;
  lastUpdated: number; // epoch seconds (0 if unknown)
  source: "onchain" | "fallback";
}

export interface OracleSnapshot {
  goldUsd: number;
  silverUsd: number;
  stablecoins: Record<string, number>;
  lastUpdated: Record<string, number>;
  source: "onchain" | "fallback";
  oracleAddress: string | null;
  rpcUrl: string;
  fetchedAt: string;
}

async function rpcCall(method: string, params: unknown[]): Promise<unknown> {
  const res = await fetch(ORACLE_RPC, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ jsonrpc: "2.0", method, params, id: 1 }),
  });
  const json = await res.json();
  if (json.error) throw new Error(`RPC error: ${json.error.message}`);
  return json.result;
}

async function ethCall(to: string, data: string): Promise<string> {
  return (await rpcCall("eth_call", [{ to, data }, "latest"])) as string;
}

function decodeUint(hex: string): bigint {
  if (!hex || hex === "0x") return 0n;
  return BigInt(hex);
}

function toUsd(wei: bigint, decimals = 8): number {
  return Number(wei) / Math.pow(10, decimals);
}

function encodeString(str: string): string {
  // ABI-encode a string for use as a function argument
  // selector (4 bytes) + offset (32 bytes) + length (32 bytes) + data (padded to 32 bytes)
  const strBytes = Buffer.from(str, "utf-8");
  const paddedLen = Math.ceil(strBytes.length / 32) * 32;
  const padded = Buffer.alloc(paddedLen);
  strBytes.copy(padded);
  const offset = 32; // offset to the start of the string data (after the offset slot)
  const length = strBytes.length;
  return (
    "0x" +
    offset.toString(16).padStart(64, "0") +
    length.toString(16).padStart(64, "0") +
    padded.toString("hex")
  );
}

/**
 * Read all prices from the on-chain MockOracle.
 * Returns null if the contract is not deployed or unreachable.
 */
export async function getOnChainOraclePrices(
  oracleAddress: string
): Promise<OracleSnapshot | null> {
  if (!oracleAddress || oracleAddress === "0x0") {
    console.log("[oracle] No oracle address configured");
    return null;
  }

  console.log("[oracle] Attempting on-chain read from:", oracleAddress);

  try {
    // Verify the contract exists
    const code = (await rpcCall("eth_getCode", [oracleAddress, "latest"])) as string;
    console.log("[oracle] Contract code length:", code?.length || 0);
    if (!code || code === "0x" || code.length < 4) {
      console.log("[oracle] No contract code at address");
      return null;
    }

    // Read gold + silver (parallel) — use the public variable getters
    // (goldPrice() and silverPrice() are auto-generated by Solidity)
    console.log("[oracle] Reading goldPrice() with selector:", SELECTORS.goldPrice);
    const [goldHex, silverHex] = await Promise.all([
      ethCall(oracleAddress, SELECTORS.goldPrice),
      ethCall(oracleAddress, SELECTORS.silverPrice),
    ]);
    console.log("[oracle] Gold hex:", goldHex);
    console.log("[oracle] Silver hex:", silverHex);

    const goldUsd = toUsd(decodeUint(goldHex));
    const silverUsd = toUsd(decodeUint(silverHex));

    // Read stablecoins (USDC, USDT, DAI) — use the mapping getter directly
    // stablecoinPrices(string) returns uint256
    const STABLECOIN_SELECTOR = "0x84176e95"; // getStablecoinPrice(string)
    const stablecoinSymbols = ["USDC", "USDT", "DAI"];
    const stablecoinResults = await Promise.all(
      stablecoinSymbols.map(async (sym) => {
        try {
          // ABI encode: selector + offset (32 bytes) + length (32 bytes) + data (padded)
          const strHex = Buffer.from(sym, "utf-8").toString("hex");
          const paddedLen = Math.ceil(strHex.length / 2) * 64; // pad to 32 bytes
          const paddedStr = strHex.padEnd(paddedLen, "0");
          const offset = "0000000000000000000000000000000000000000000000000000000000000020"; // 32 bytes offset
          const length = (sym.length).toString(16).padStart(64, "0");
          const fullData = STABLECOIN_SELECTOR + offset + length + paddedStr;
          const priceHex = await ethCall(oracleAddress, fullData);
          return {
            symbol: sym,
            price: toUsd(decodeUint(priceHex)),
            lastUpdated: Math.floor(Date.now() / 1000),
          };
        } catch {
          // If stablecoin read fails, default to $1
          return { symbol: sym, price: 1, lastUpdated: Math.floor(Date.now() / 1000) };
        }
      })
    );

    const stablecoins: Record<string, number> = {};
    const lastUpdated: Record<string, number> = {};
    for (const sc of stablecoinResults) {
      stablecoins[sc.symbol] = sc.price;
      lastUpdated[sc.symbol] = sc.lastUpdated;
    }
    lastUpdated["GOLD"] = Math.floor(Date.now() / 1000);
    lastUpdated["SILVER"] = Math.floor(Date.now() / 1000);

    return {
      goldUsd,
      silverUsd,
      stablecoins,
      lastUpdated,
      source: "onchain",
      oracleAddress,
      rpcUrl: ORACLE_RPC,
      fetchedAt: new Date().toISOString(),
    };
  } catch (err) {
    console.warn("[oracle] on-chain read failed, will use fallback:", err instanceof Error ? err.message : err);
    return null;
  }
}

/**
 * Get the current oracle snapshot.
 *
 * Strategy (per §30 oracle engine):
 *   1. If MOCK_ORACLE_ADDRESS env var is set, try reading from the on-chain contract.
 *   2. If on-chain read fails OR the address is not set, fall back to live free APIs.
 *
 * This allows the dashboard to show real prices immediately, then transparently
 * switch to on-chain prices once the MockOracle is deployed.
 */
export async function getOracleSnapshot(): Promise<OracleSnapshot> {
  const oracleAddress = process.env.MOCK_ORACLE_ADDRESS;

  // Try on-chain first (if address is configured)
  if (oracleAddress) {
    const onChain = await getOnChainOraclePrices(oracleAddress);
    if (onChain && onChain.goldUsd > 0) {
      return onChain;
    }
  }

  // Fallback: live free APIs (gold-api.com, open.er-api.com)
  return getFallbackOracleSnapshot();
}

/**
 * Fallback oracle: fetch live prices from free public APIs.
 * Used when MockOracle is not yet deployed, or as a redundancy check.
 */
async function getFallbackOracleSnapshot(): Promise<OracleSnapshot> {
  try {
    // Gold price from gold-api.com (free, no key) — uses api. subdomain
    const goldRes = await fetch("https://api.gold-api.com/price/XAU", {
      signal: AbortSignal.timeout(5000),
    });
    const goldData = await goldRes.json();
    const goldUsd = typeof goldData.price === "number" ? goldData.price : 4053.70;

    // Silver price (free, no key) — same API, XAG symbol
    let silverUsd = 25; // reasonable default
    try {
      const silverRes = await fetch("https://api.gold-api.com/price/XAG", {
        signal: AbortSignal.timeout(5000),
      });
      if (silverRes.ok) {
        const text = await silverRes.text();
        // Only parse as JSON if it looks like JSON (not HTML)
        if (text.trim().startsWith("{")) {
          const silverData = JSON.parse(text);
          if (typeof silverData.price === "number") silverUsd = silverData.price;
        }
      }
    } catch {
      // keep default
    }

    const now = Math.floor(Date.now() / 1000);
    return {
      goldUsd,
      silverUsd,
      stablecoins: { USDC: 1, USDT: 1, DAI: 1 },
      lastUpdated: { GOLD: now, SILVER: now, USDC: now, USDT: now, DAI: now },
      source: "fallback",
      oracleAddress: null,
      rpcUrl: ORACLE_RPC,
      fetchedAt: new Date().toISOString(),
    };
  } catch (err) {
    console.warn("[oracle] fallback API failed, using defaults:", err);
    const now = Math.floor(Date.now() / 1000);
    return {
      goldUsd: 4053.70, // last known
      silverUsd: 25,
      stablecoins: { USDC: 1, USDT: 1, DAI: 1 },
      lastUpdated: { GOLD: now, SILVER: now, USDC: now, USDT: now, DAI: now },
      source: "fallback",
      oracleAddress: null,
      rpcUrl: ORACLE_RPC,
      fetchedAt: new Date().toISOString(),
    };
  }
}

/**
 * Format a USD price as the 8-decimal uint256 expected by MockOracle.sol.
 * e.g., 4053.50 → "405350000000"
 */
export function priceToWei(usd: number): string {
  const wei = Math.round(usd * 1e8);
  return wei.toString();
}

/**
 * Parse a uint256 price (8 decimals) from MockOracle.sol into USD.
 */
export function weiToPrice(wei: string | bigint): number {
  return Number(wei) / 1e8;
}
