// src/app/api/evidence-archive/route.ts
//
// MITHQAL v25.3.22 — Neon S3 Evidence Archive API (CR-2026-027 — Proposal B)
//
//   POST   /api/evidence-archive     — archive a 15-field EvidencePackage to S3
//   GET    /api/evidence-archive     — list archived S3 keys (optional ?prefix=)
//
// HONEST-STATE NOTE (CRITICAL):
//   S3 archive is DURABLE STORAGE, not a substitute for institutional
//   validation. Archiving ≠ validation.
//
//   A successful POST response (HTTP 200 + `archived: true`) proves ONLY that
//   the package was persisted to S3. It does NOT constitute legal,
//   regulatory, accounting, or audit sign-off. The underlying transaction
//   remains subject to the access-gated retrieval rules enforced by
//   `retrieveEvidencePackage(transactionId, accessLevel)` in
//   institutional-evidence-fabric.ts (PUBLIC / INSTITUTIONAL / AUDIT).
//
// NOT PRODUCTION-AUTHORIZED.
//
// The EvidencePackage type (15 fields + 3 access levels) is FROZEN per
// controlled-architecture-freeze.ts. This route imports the type — it does
// NOT redefine or extend it.

import { NextResponse } from "next/server";
import { enforceRateLimit } from "@/lib/rate-limit";
import {
  archiveEvidencePackage,
  retrieveEvidencePackage,
  listEvidencePackages,
  getEvidenceArchiveConfigStatus,
  EVIDENCE_ARCHIVE_VERSION,
  EVIDENCE_ARCHIVE_SOURCE,
  EVIDENCE_ARCHIVE_STATUS,
} from "@/lib/evidence-archive";
import {
  EVIDENCE_PACKAGE_FIELDS,
  EVIDENCE_PACKAGE_FIELD_COUNT,
  type EvidencePackage,
} from "@/lib/institutional-evidence-fabric";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

// === GET /api/evidence-archive ===
//
// Query params:
//   ?prefix=foo   — restrict list to keys with the given prefix (default: "evidence/")
//   ?key=...      — retrieve a single archived package by S3 key
//   ?status=true  — return the archive's configuration + honest-state snapshot
//
// Without params: list archived keys (paged on the S3 side, capped at 5000 keys
// server-side by listEvidencePackages).

export async function GET(request: Request) {
  const rateLimited = enforceRateLimit("evidence-archive-get", request, 30, 60_000);
  if (rateLimited) return rateLimited;

  const url = new URL(request.url);
  const prefix = url.searchParams.get("prefix") ?? undefined;
  const key = url.searchParams.get("key");
  const statusOnly = url.searchParams.get("status") === "true";

  if (statusOnly) {
    return NextResponse.json({
      _meta: {
        activeModel: "v25.3.22",
        source: EVIDENCE_ARCHIVE_SOURCE,
        version: EVIDENCE_ARCHIVE_VERSION,
        status: EVIDENCE_ARCHIVE_STATUS,
      },
      config: getEvidenceArchiveConfigStatus(),
      rule: "POST a 15-field EvidencePackage to archive it. GET ?key=... to retrieve. GET ?prefix=... to list. All retrieval returns the full unredacted package — apply access-level gating via the evidence-fabric API before exposing to end users.",
    });
  }

  // Retrieve a single archived package by S3 key.
  if (key) {
    const pkg = await retrieveEvidencePackage(key);
    if (!pkg) {
      return NextResponse.json(
        {
          _meta: {
            activeModel: "v25.3.22",
            source: EVIDENCE_ARCHIVE_SOURCE,
            version: EVIDENCE_ARCHIVE_VERSION,
            status: EVIDENCE_ARCHIVE_STATUS,
          },
          error: `Archived package not found for key: ${key}`,
          honestState:
            "S3 archive is DURABLE STORAGE, not a substitute for institutional validation. Archiving ≠ validation.",
        },
        { status: 404 }
      );
    }
    return NextResponse.json({
      _meta: {
        activeModel: "v25.3.22",
        source: EVIDENCE_ARCHIVE_SOURCE,
        version: EVIDENCE_ARCHIVE_VERSION,
        status: EVIDENCE_ARCHIVE_STATUS,
      },
      s3Key: key,
      evidencePackage: pkg,
      retrievalWarning:
        "Returned package is UNREDACTED. Apply access-level gating (PUBLIC / INSTITUTIONAL / AUDIT) via retrieveEvidencePackage(transactionId, accessLevel) in institutional-evidence-fabric.ts before exposing to end users.",
    });
  }

  // List archived keys.
  const keys = await listEvidencePackages(prefix);
  return NextResponse.json({
    _meta: {
      activeModel: "v25.3.22",
      source: EVIDENCE_ARCHIVE_SOURCE,
      version: EVIDENCE_ARCHIVE_VERSION,
      status: EVIDENCE_ARCHIVE_STATUS,
    },
    prefix: prefix ?? "evidence/",
    keys,
    count: keys.length,
    honestState:
      "S3 archive is DURABLE STORAGE, not a substitute for institutional validation. Archiving ≠ validation.",
  });
}

// === POST /api/evidence-archive ===
//
// Body: a 15-field EvidencePackage (JSON). The package must already have
// been generated by `generateEvidencePackage(...)` in
// institutional-evidence-fabric.ts — i.e., it must carry valid
// cryptographicCommitments. This endpoint does NOT regenerate or re-sign
// anything; it only persists the submitted package to S3.
//
// Idempotent: re-POSTing the same package overwrites the same S3 key
// (content-addressed by fullPackageCommitment).

export async function POST(request: Request) {
  const rateLimited = enforceRateLimit("evidence-archive-post", request, 10, 60_000);
  if (rateLimited) return rateLimited;

  try {
    const body = (await request.json()) as Partial<EvidencePackage>;
    // Validate that the body carries all 15 frozen fields before archiving.
    // The EvidencePackage schema is FROZEN — do NOT accept partials.
    const missing: string[] = [];
    for (const field of EVIDENCE_PACKAGE_FIELDS) {
      if (!(field in (body as Record<string, unknown>))) {
        missing.push(field);
      }
    }
    if (missing.length > 0) {
      return NextResponse.json(
        {
          _meta: {
            activeModel: "v25.3.22",
            source: EVIDENCE_ARCHIVE_SOURCE,
            version: EVIDENCE_ARCHIVE_VERSION,
            status: EVIDENCE_ARCHIVE_STATUS,
          },
          error: `Submitted evidence package is missing required frozen field(s): ${missing.join(", ")}`,
          expectedFieldCount: EVIDENCE_PACKAGE_FIELD_COUNT,
          missing,
        },
        { status: 400 }
      );
    }

    // Defensive: ensure the cryptographic commitment used to derive the S3
    // key is present. A package generated by the canonical fabric will
    // always carry this; rejecting absent commitments prevents key collisions
    // and accidental overwrites of unrelated packages.
    const commitment =
      body.cryptographicCommitments?.fullPackageCommitment ||
      body.cryptographicCommitments?.transactionIdCommitment;
    if (!commitment) {
      return NextResponse.json(
        {
          _meta: {
            activeModel: "v25.3.22",
            source: EVIDENCE_ARCHIVE_SOURCE,
            version: EVIDENCE_ARCHIVE_VERSION,
            status: EVIDENCE_ARCHIVE_STATUS,
          },
          error:
            "Submitted evidence package is missing cryptographicCommitments.fullPackageCommitment — cannot derive content-addressed S3 key.",
        },
        { status: 400 }
      );
    }

    const result = await archiveEvidencePackage(body as EvidencePackage);

    const status = result.archived ? 200 : 503;
    return NextResponse.json(
      {
        _meta: {
          activeModel: "v25.3.22",
          source: EVIDENCE_ARCHIVE_SOURCE,
          version: EVIDENCE_ARCHIVE_VERSION,
          status: EVIDENCE_ARCHIVE_STATUS,
        },
        s3Key: result.s3Key,
        archivedAt: result.archivedAt,
        archived: result.archived,
        error: result.error,
        honestState:
          "S3 archive is DURABLE STORAGE, not a substitute for institutional validation. Archiving ≠ validation.",
        rule: "Re-POSTing the same package is idempotent (content-addressed by fullPackageCommitment). Apply access-level gating before exposing the archived package to end users.",
      },
      { status }
    );
  } catch (err) {
    return NextResponse.json(
      {
        _meta: {
          activeModel: "v25.3.22",
          source: EVIDENCE_ARCHIVE_SOURCE,
          version: EVIDENCE_ARCHIVE_VERSION,
          status: EVIDENCE_ARCHIVE_STATUS,
        },
        error: "Failed to archive evidence package",
        detail: err instanceof Error ? err.message : "unknown",
      },
      { status: 500 }
    );
  }
}
